### ISSUE TITLE
include CAN_DETECT and CAN_FIX

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/bear-docs#3]
those will be added to bear soon (I hope today) and then we'll want them here ASAP :)

**Comment by hypothesist** [comment]
They'll be available in somewhere like `bear.get_metadata()`? Sorry, haven't been following the new feature :)

**Comment by sils1297** [comment]
no, it'll be a classproperty, just like `supported_languages`

**Comment by hypothesist** [comment]
Closed from https://github.com/coala-analyzer/bear-docs/commit/f6064f9384b42ea70486d71f070890a557fcb3cb

Although no bear has CAN_FIX and CAN_DETECT I think
